### ISSUE TITLE
Bien resuelta la entrega, has cumplido muy bien con los objetivos

### ISSUE THREAD

**Issue by vicenlu** [LaraBerenguer/typescript-api-jokes-site#4]
Que son dar tus primeros pasos en typescript, y comenzar a usar APIs de terceros

https://github.com/LaraBerenguer/typescript-api-jokes-site/blob/2923c64c5b3fc0e219e1a85b575d9f0fc2a602e7/index.ts#L81

**Comment by LaraBerenguer** [comment]
Genial Luis! Voy a corregir los issues que me has comentado. Sobre todo las variables de entorno del proyecto que no me sonaban pero me interesan. Iré cerrando según lo haga 👍🏼 Muchas gracias!
